### ISSUE TITLE
Popup is shown on the wrong line if file is edited

### ISSUE THREAD

**Issue by sekjun9878** [bblanchon/SublimeText-HighlightBuildErrors#21]
![screenshot from 2016-03-05 03 08 19](https://cloud.githubusercontent.com/assets/2097812/13533304/d26db638-e27f-11e5-8131-e0b663737b1f.png)

And this is after the views are updated (e.g. re-focusing the window will re-draw all the popups which causes this, which is incorrect)
![screenshot from 2016-03-05 03 06 46](https://cloud.githubusercontent.com/assets/2097812/13533303/d26a4b4c-e27f-11e5-9a54-c8a4969c0738.png)

Some kind of heuristics might be needed to keep the popup at the correct location even after the file is edited, or remove all highlights with a message if it's unrecoverable.

**Comment by Hoten** [comment]
One solution that might work would be to look for the nearest line of code that matches the code that created the error. Cap it to only look at the nearest 100 lines so that it doesn't kill performance. Not very elegant, though, and very large edits would lose you the error.

or, with every line count change (addition or removal of a newline), we could recalculate where the pop up boxes should be. that would probably work better. actually, it would have to be with every keystroke, since the popup error could move horizontally.

**Comment by bblanchon** [comment]
I'm closing this issue because I removed the popup feature since Sublime Text 3 now has a similar built-in feature.
