### ISSUE TITLE
colour setting not working

### ISSUE THREAD

**Issue by zimmertyzim** [bblanchon/SublimeText-HighlightBuildErrors#5]
I don't know if this is me being straight up dumb, but I can only get two colours to display. Either white, or the default pink.

Am I missing something here?

**Comment by bblanchon** [comment]
It's kind of tricky.
Despite of the name "error_color", it's a key to a color in the selected theme.
This kind of key is called "scope" and you can see them in the `.tmTheme` files.

For instance, you can use the scope used for SublimeLinter's error:

	{
		"error_color": "sublimelinter.mark.error"
	}

**Comment by zimmertyzim** [comment]
ah, that makes much more sense.

thanks. I'm new to all of this stuff. I'll give it a whirl.

**Comment by vexe** [comment]
Could somebody elaborate more on this? Where exactly do I change/add this "error_color" value? - I see a "error_color" in "SublimeLinter.sublime-settings" but changing it doesn't do anything. I don't get anything when searching for "error" in my tmTheme files.

**Comment by bblanchon** [comment]
It's on `HighlightBuildErrors.sublime-settings`.

You can open this file from the menu: `Preferences` > `Package Settings` > `Highlight Build Errors`.

**Comment by vexe** [comment]
I did mention in my previous message that I already tried the error_color in HighlightBuildErrors.sublime-settings setting it to "ff0000" but to no avail - highlight stays white. Any ideas? (using ST3)

**Comment by bblanchon** [comment]
Color code don't work here, as it's written above:

> Despite of the name "error_color", it's a key to a color in the selected theme.
> This kind of key is called "scope" and you can see them in the .tmTheme files.

The example of `sublimelinter.mark.error` only works if your theme defines it.
This is not the case of the default [Monokai theme](https://github.com/cj/sublime/blob/master/Color%20Scheme%20-%20Default/Monokai.tmTheme), but many other themes (like [Gravity](https://github.com/frankyonnetti/gravity-sublime-theme/blob/master/Monokai%20Gravity%20(SL).tmTheme#L1850)) have it because it's a very popular plugin.
